<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3xxUBxd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3xxUBxd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3xxUBxd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3xxUBxd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3xxUBxd\App_KernelDevDebugContainer([
    'container.build_hash' => '3xxUBxd',
    'container.build_id' => 'a18c0cfb',
    'container.build_time' => 1609709907,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3xxUBxd');
